### ISSUE TITLE
blog.naaln.com/source/_posts/2019-04-hark-iPac.md

### ISSUE THREAD

**Issue by JerryChenn07** [liszd/blog.naaln.com#1]
这个你测试成功了么，iP*c这个你的版本是哪个呢？

**Comment by whyliam** [comment]
可以使用的 1.6.8

**Comment by Jerry007s** [comment]
没有成功唉，刚又重装了一下，完全按照步骤使用，全部命令如下，可以帮忙排查下吗，谢谢

 ~  mkdir -p /Applications/cipc.app/MacOS/
 ~  vim  /Applications/cipc.app/MacOS/cipc
 ~  chmod +x /Applications/cipc.app/MacOS/cipc
 ~  cat /Applications/cipc.app/MacOS/cipc
!/bin/bash
/usr/libexec/PlistBuddy -c "Set ':values:Markdown Flag:value' `date +%s`" /Users/`whoami`/Library/Containers/net.toolinbox.ipic/Data/Library/SyncedPreferences/net.toolinbox.ipic.plist && nohup /Applications/iPic.app/Contents/MacOS/iPic &

**Comment by Jerry007s** [comment]
mkdir -p /Applications/cipc.app/MacOS/    这里是cipc.app么？感觉不太对吧

**Comment by whyliam** [comment]
看一下里面的时间戳对不对 /Users/yourname/Library/Containers/net.toolinbox.ipic/Data/Library/SyncedPreferences/net.toolinbox.ipic.plist

原理就是修改这个时间戳，这个至少其中一种修改方法而已

**Comment by Jerry007s** [comment]
最后我手动去执行那个脚本，发现成功了，但是感觉`mkdir -p /Applications/cipc.app/MacOS/`中的`cipc.app`这个是不是错了。。。

**Comment by whyliam** [comment]
嗯，我现在没有用建cipc.app的方法，调用的方法有很多种，原理都是一样的，可以找一个自己习惯的方式。
